database:
  host: localhost
  port: 5432
  name: your_database
  user: your_user
  password: your_password

model:
  embedding_size: 768
  max_sequence_length: 512
  batch_size: 32

exploration:
  initial_exploration_rate: 0.3
  min_exploration_rate: 0.05
  decay_rate: 0.995

knowledge_graph:
  min_relationship_weight: 0.1
  max_relationship_distance: 3

logging:
  level: INFO
  file: logs/continuous_query_explorer.log
